### ISSUE TITLE
Budgetapp dont Save 

### ISSUE THREAD

**Issue by elisa9180** [paukiatwee/budgetapp#11]
When restart the Run.sh file or reboot Server
All input data. and the created account are gone.

what am I doing wrong

**Comment by elisa9180** [comment]
Pleas tutorial for setting up database on linux

**Comment by paukiatwee** [comment]
You need setup PostgreSQL via package manager of your favored distro, such as Ubuntu or Fedora.

For any configurable parameters, you can refer to docs https://budgetapp.docsapp.io/docs/configuration

You can edit `run.sh` to export any parameters:

```
#!/bin/sh

mvn clean package

export DB_DRIVER=org.postgresql.Driver
export DB_USERNAME=<USERNAME>
export DB_PASSWORD=<PASSWORD>
export DB_URL=jdbc:postgresql://<DB_SERVER>/<DB_NAME>
export DB_DIALECT=io.budgetapp.hibernate.dialect.CustomPostgreSQLDialect

java -Duser.timezone=UTC -jar target/budgetapp.jar server config/config.yml

```
