### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by shimuranmonk** [paukiatwee/budgetapp#14]
Hi. I can't seem to install this app on a shared hosting in Hostgator.  Something is a miss.  How should I or are there steps into installing this to a hosting service like hostgator?

**Comment by rustydr34m** [comment]
1) install maven
https://tecadmin.net/install-apache-maven-on-ubuntu/#

2)Build app
https://budgetapp.docsapp.io/docs/local

**Comment by paukiatwee** [comment]
rustydr34m  provided help on how to install budgetapp locally.
