### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by rphillips** [paukiatwee/budgetapp#7]
Greetings,

I tried out the demo link and built from source. Both methods are showing a blank page; however, view->source within the browser is showing a bunch of html markup. Not sure what is going on.

**Comment by paukiatwee** [comment]
What is your OS and browser?
Can you check whether your browser shows any error?

**Comment by rphillips** [comment]
OSX, Google Chrome  51.0.2704.103

**Comment by rphillips** [comment]
Firefox 47.0.1 on OSX has the same issue as well... I tried the demo site at https://app.budgetapp.io/

**Comment by paukiatwee** [comment]
I dont have Mac OS so I cant test and debug.

**Comment by navneetkarnani** [comment]
I looked at the problem on my mac (and Safari). There seems to be a combination of things I tried, and now it seems to work. I don't know which set of changes are sufficient in themselves. I will generate the pull request and let @paukiatwee decide which needs to be integrated.

**Comment by navneetkarnani** [comment]
This should now be fixed. @rphillips Can you please validate ?

**Comment by paukiatwee** [comment]
No response from reporter. Close this.
